### ISSUE TITLE
Error: This method is not implemented in DominoAdapter: getCookie

### ISSUE THREAD

**Issue by sathishvikkas** [fgnass/domino#143] opened 2019-09-27 07:52 UTC
Error: This method is not implemented in DominoAdapter: getCookie
at _notImplemented (E:\myapp\src\main\kiosk\dist\server\main.js:251176:16)
at DominoAdapter.getCookie (E:\myapp\src\main\kiosk\dist\server\main.js:251367:69)

**Comment by CaerusKaru** [comment] 2019-11-15 21:09
Duplicate of https://github.com/fgnass/domino/issues/132

**Comment by cscott** [comment] 2019-12-16 20:45
Closing as duplicate.

**Closed by cscott** 2019-12-16 20:45 UTC
