### ISSUE TITLE
Getting error with Domino while running Angular Universal SSR app

### ISSUE THREAD

**Issue by dexbytesmanish** [fgnass/domino#132] opened 2018-11-22 11:38 UTC
Getting following error while running Angular App with Universal SSR :

ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
    at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
    at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
    at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
    at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
    at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
    at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
    at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
    at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
    at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
    at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117362:31)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117319:17)
    at /var/www/html/project-angular6/dist/server.js:117421:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116969:31)
    at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116968:36)
    at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116736:47)
    at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117143:35)
    at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117048:21)
    at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:117033:48)
  rejection:
   Error: This method is not implemented in DominoAdapter: getCookie
       at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
       at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
       at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
       at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
       at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
       at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
       at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
       at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
       at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
       at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      Error: This method is not implemented in DominoAdapter: getCookie
          at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
          at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
          at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
          at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
          at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
          at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
          at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
          at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
          at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
          at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         Error: This method is not implemented in DominoAdapter: getCookie
             at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
             at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
             at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
             at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
             at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
             at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
             at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
             at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
             at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
             at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
(node:7532) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
    at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
    at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
    at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
    at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
    at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
    at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
    at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
    at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
    at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
    at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117362:31)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117319:17)
    at /var/www/html/project-angular6/dist/server.js:117421:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116969:31)
    at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116968:36)
    at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116736:47)
    at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117143:35)
    at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117048:21)
    at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:117033:48)
  rejection:
   Error: This method is not implemented in DominoAdapter: getCookie
       at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
       at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
       at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
       at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
       at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
       at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
       at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
       at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
       at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
       at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      Error: This method is not implemented in DominoAdapter: getCookie
          at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
          at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
          at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
          at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
          at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
          at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
          at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
          at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
          at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
          at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         Error: This method is not implemented in DominoAdapter: getCookie
             at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
             at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
             at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
             at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
             at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
             at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
             at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
             at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
             at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
             at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
ERROR { Error: Uncaught (in promise): Error: This method is not implemented in DominoAdapter: getCookie
Error: This method is not implemented in DominoAdapter: getCookie
    at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
    at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
    at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
    at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
    at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
    at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
    at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
    at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
    at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
    at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117362:31)
    at resolvePromise (/var/www/html/project-angular6/dist/server.js:117319:17)
    at /var/www/html/project-angular6/dist/server.js:117421:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116969:31)
    at Object.onInvokeTask (/var/www/html/project-angular6/dist/server.js:4204:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/var/www/html/project-angular6/dist/server.js:116968:36)
    at Zone.module.exports.Zone.runTask (/var/www/html/project-angular6/dist/server.js:116736:47)
    at drainMicroTaskQueue (/var/www/html/project-angular6/dist/server.js:117143:35)
    at module.exports.ZoneTask.invokeTask (/var/www/html/project-angular6/dist/server.js:117048:21)
    at Server.ZoneTask.invoke (/var/www/html/project-angular6/dist/server.js:117033:48)
  rejection:
   Error: This method is not implemented in DominoAdapter: getCookie
       at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
       at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
       at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
       at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
       at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
       at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
       at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
       at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
       at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
       at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14),
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      Error: This method is not implemented in DominoAdapter: getCookie
          at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
          at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
          at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
          at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
          at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
          at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
          at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
          at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
          at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
          at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [ZoneDelegate] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [ZoneDelegate],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Zone],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Zone],
        _invokeZS: [Object],
        _invokeDlgt: [ZoneDelegate],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [ZoneDelegate],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [ZoneDelegate],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [ZoneDelegate],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [ZoneDelegate],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [ZoneDelegate],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Zone],
        _name: 'angular',
        _zoneDelegate: [ZoneDelegate] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data:
      ZoneAwarePromise {
        __zone_symbol__state: 0,
        __zone_symbol__value:
         Error: This method is not implemented in DominoAdapter: getCookie
             at _notImplemented (/var/www/html/project-angular6/dist/server.js:87272:12)
             at DominoAdapter.module.exports.DominoAdapter.getCookie (/var/www/html/project-angular6/dist/server.js:87463:65)
             at CookieXSRFStrategy.module.exports.CookieXSRFStrategy.configureRequest (/var/www/html/project-angular6/dist/server.js:76600:101)
             at XHRBackend.module.exports.XHRBackend.createConnection (/var/www/html/project-angular6/dist/server.js:76641:28)
             at httpRequest (/var/www/html/project-angular6/dist/server.js:77008:20)
             at Http.module.exports.Http.request (/var/www/html/project-angular6/dist/server.js:77106:34)
             at Http.module.exports.Http.get (/var/www/html/project-angular6/dist/server.js:77117:21)
             at topbannerService.module.exports../src/app/home/top-banner/top-banner.service.ts.topbannerService.getTopFeatureData (/var/www/html/project-angular6/dist/server.js:154860:26)
             at TopBannerComponent.module.exports../src/app/home/top-banner/top-banner.component.ts.TopBannerComponent.getTopFeaturedArtworks (/var/www/html/project-angular6/dist/server.js:154815:31)
             at new TopBannerComponent (/var/www/html/project-angular6/dist/server.js:154811:14) },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }

**Comment by cscott** [comment] 2018-11-26 19:16
This seems like a bug in DominoAdapter (whatever that is), not in domino.  Could you refile this bug against a more-appropriate package (maybe angular)?

**Comment by CaerusKaru** [comment] 2018-11-27 03:32
@cscott This is a duplicate of https://github.com/angular/universal/issues/1094 and can be closed.

**Closed** 2018-11-27 03:37 UTC

**Comment by dexbytesmanish** [comment] 2018-11-27 05:40
I already reported this issue on Angular and Universal repository but they
are not accepting it as DominoAdaptor issue and it seems funny nobody is
able to solution to this issue.
